export type ChallengeType = "algebra" | "2-var" | "3-var";

export interface Challenge {
  toolId: string;
  href: string;
  type: ChallengeType;
  equation1: string;
  equation2?: string;
  equation3?: string;
}

interface ChallengeBankEntry {
  toolId: string;
  href: string;
  type: ChallengeType;
  pool: Array<Pick<Challenge, "equation1" | "equation2" | "equation3">>;
}

const CHALLENGE_BANK: Record<string, ChallengeBankEntry[]> = {
  algebra: [
    {
      toolId: "linearEquations",
      href: "/mathematics/linear-equations",
      type: "algebra",
      pool: [
        { equation1: "3x + 5 = 2x + 12" },
        { equation1: "4*(x - 3) = 2x + 6" },
        { equation1: "6x - 7 = 4x + 9" },
        { equation1: "x/3 + 2 = 5" },
        { equation1: "7x - 2 = 3x + 18" },
        { equation1: "5x + 4 = 3x + 14" },
        { equation1: "2*(x + 4) = 3x - 1" },
        { equation1: "8x - 3 = 5x + 15" },
        { equation1: "x/4 + 3 = 7" },
        { equation1: "9x - 5 = 4x + 20" },
        { equation1: "3*(x - 5) = x + 3" },
        { equation1: "10x + 1 = 6x + 21" },
        { equation1: "4x + 6 = 22" },
        { equation1: "5*(x - 4) = 15" },
        { equation1: "8x - 3 = 4x + 13" },
        { equation1: "x/4 + 1/2 = 6" },
        { equation1: "6x + 9 = 33" },
        { equation1: "7*(x + 2) = 28" },
        { equation1: "9x - 4 = 5x + 16" },
        { equation1: "|4x - 5| = 11" },
        { equation1: "12x - 8 = 7x + 27" },
        { equation1: "6*(2x - 3) = 4*(x + 6)" },
        { equation1: "x/6 + 5 = 12" },
        { equation1: "15x + 4 = 9x + 40" },
        { equation1: "3*(x + 7) - 5 = 2*(x + 10)" },
        { equation1: "x/3 - 1/2 = 4" },
        { equation1: "20x - 15 = 13x + 20" },
        { equation1: "|5x + 3| = 18" },
        { equation1: "9*(x - 6) = 4x - 9" },
        { equation1: "11x + 7 = 4x + 49" },
      ],
    },
    {
      toolId: "quadraticEquations",
      href: "/mathematics/quadratic-equations",
      type: "algebra",
      pool: [
        { equation1: "x^2 - 7x + 10 = 0" },
        { equation1: "x^2 + 6x = -8" },
        { equation1: "x^2 - 6x + 9 = 0" },
        { equation1: "x^2 + 4x + 13 = 0" },
        { equation1: "3x^2 - 12 = 0" },
        { equation1: "x^2 - 9x + 20 = 0" },
        { equation1: "x^2 + 8x = -15" },
        { equation1: "x^2 - 10x + 25 = 0" },
        { equation1: "x^2 + 2x + 10 = 0" },
        { equation1: "2x^2 - 18 = 0" },
        { equation1: "x^2 - 3x - 4 = 0" },
        { equation1: "x^2 + 7x + 12 = 0" },
        { equation1: "x^2 - 5x - 6 = 0" },
        { equation1: "x^2 + 9x + 18 = 0" },
        { equation1: "2x^2 + 3x - 2 = 0" },
        { equation1: "4x^2 - 4x + 1 = 0" },
        { equation1: "x^2 + 5x + 20 = 0" },
        { equation1: "x^2 - 2x - 15 = 0" },
        { equation1: "5x^2 - 20 = 0" },
        { equation1: "x^2 - 11x + 30 = 0" },
        { equation1: "x^2 - 13x + 40 = 0" },
        { equation1: "x^2 + 11x + 24 = 0" },
        { equation1: "3x^2 - 5x - 2 = 0" },
        { equation1: "6x^2 - 7x + 2 = 0" },
        { equation1: "x^2 + 6x + 25 = 0" },
        { equation1: "x^2 - 4x - 21 = 0" },
        { equation1: "7x^2 - 28 = 0" },
        { equation1: "x^2 - 14x + 49 = 0" },
        { equation1: "2x^2 + 7x + 3 = 0" },
        { equation1: "x^2 + 3x - 40 = 0" },
      ],
    },
    {
      toolId: "logarithmicEquations",
      href: "/mathematics/logarithmic-equations",
      type: "algebra",
      pool: [
        { equation1: "log_2(x+5) + log_2(x-3) = 5" },
        { equation1: "log(x+5) - log(x-2) = 1" },
        { equation1: "ln(x) + ln(x-3) = ln(4)" },
        { equation1: "log_3(x^2-4) = 2" },
        { equation1: "ln(x) = 3" },
        { equation1: "log_2(x+7) + log_2(x-1) = 3" },
        { equation1: "log(x+3) - log(x-1) = 1" },
        { equation1: "ln(x) + ln(x-4) = ln(5)" },
        { equation1: "log_3(x^2-9) = 2" },
        { equation1: "ln(x) = 4" },
        { equation1: "log_2(x-2) + log_2(x+2) = 5" },
        { equation1: "log_5(x+4) = 2" },
        { equation1: "log_2(x) = 5" },
        { equation1: "log(x) = 2" },
        { equation1: "ln(x-1) = 2" },
        { equation1: "log_2(x+9) + log_2(x-7) = 4" },
        { equation1: "log(x+7) - log(x-3) = 1" },
        { equation1: "ln(x) + ln(x-5) = ln(6)" },
        { equation1: "log_3(x^2-16) = 2" },
        { equation1: "log_4(x+12) = 2" },
        { equation1: "log_2(x+11) + log_2(x-5) = 4" },
        { equation1: "log(x+9) - log(x-3) = 1" },
        { equation1: "ln(x) + ln(x-6) = ln(7)" },
        { equation1: "log_3(x^2-25) = 2" },
        { equation1: "ln(x) = 5" },
        { equation1: "log_2(x-4) + log_2(x+4) = 5" },
        { equation1: "log_6(x+9) = 2" },
        { equation1: "log(x+2) - log(x-4) = 1" },
        { equation1: "log_2(x) = 6" },
        { equation1: "ln(x-2) = 3" },
      ],
    },
    {
      toolId: "powersAlgebra",
      href: "/mathematics/exponents-algebra",
      type: "algebra",
      pool: [
        { equation1: "x^3 * x^2" },
        { equation1: "(x^3)^2" },
        { equation1: "x^-3" },
        { equation1: "(x+2)*(x-2)" },
        { equation1: "3x+4=13" },
        { equation1: "2^(2x)+2^x-12=0" },
        { equation1: "x^4 * x^2" },
        { equation1: "(x^2)^4" },
        { equation1: "x^-4" },
        { equation1: "(x+3)*(x-3)" },
        { equation1: "5x+2=17" },
        { equation1: "2^(2x)+2^x-20=0" },
        { equation1: "x^5 * x^3" },
        { equation1: "(x^4)^2" },
        { equation1: "x^-5" },
        { equation1: "(x+4)*(x-4)" },
        { equation1: "6x+3=27" },
        { equation1: "x^2=25" },
        { equation1: "x^3=64" },
        { equation1: "sqrt(2^X) = 8" },
        { equation1: "x^6 * x^2" },
        { equation1: "(x^5)^2" },
        { equation1: "x^-6" },
        { equation1: "(x+5)*(x-5)" },
        { equation1: "7x+5=40" },
        { equation1: "x^2=49" },
        { equation1: "x^3=125" },
        { equation1: "sqrt(3^X) = 27" },
        { equation1: "2^(2x)+2^x-30=0" },
        { equation1: "(x^3)^3" },
      ],
    },
    {
      toolId: "functionAnalysis",
      href: "/mathematics/function-analysis",
      type: "algebra",
      pool: [
        { equation1: "x^3 - 4x^2" },
        { equation1: "x^3 - 4x + 2" },
        { equation1: "x^4 - 9x^2" },
        { equation1: "-x^2 + 6x" },
        { equation1: "x^3 - 9x^2 + 20x" },
        { equation1: "x^3 - 5x^2" },
        { equation1: "x^3 - 5x + 3" },
        { equation1: "x^4 - 16x^2" },
        { equation1: "-x^2 + 8x" },
        { equation1: "x^3 - 12x^2 + 36x" },
        { equation1: "x^3 + 3x^2" },
        { equation1: "x^4 - 4x^2 + 3" },
        { equation1: "x^3 - 6x^2" },
        { equation1: "x^3 - 6x + 4" },
        { equation1: "x^4 - 25x^2" },
        { equation1: "-x^2 + 10x" },
        { equation1: "x^3 - 15x^2 + 56x" },
        { equation1: "x^3 + 4x^2" },
        { equation1: "x^4 - 6x^2 + 5" },
        { equation1: "x^3 - 7x^2 + 10x" },
        { equation1: "x^3 - 8x^2" },
        { equation1: "x^3 - 8x + 6" },
        { equation1: "x^4 - 36x^2" },
        { equation1: "-x^2 + 12x" },
        { equation1: "x^3 - 18x^2 + 80x" },
        { equation1: "x^3 + 5x^2" },
        { equation1: "x^4 - 8x^2 + 7" },
        { equation1: "x^3 - 10x^2 + 21x" },
        { equation1: "x^4 - 49x^2" },
        { equation1: "-x^2 + 14x" },
      ],
    },
    {
      toolId: "systemOfEquations",
      href: "/mathematics/system-of-equations",
      type: "2-var",
      pool: [
        { equation1: "x + y = 8", equation2: "2x - y = 4" },
        { equation1: "3x + 2y = 16", equation2: "x - y = 2" },
        { equation1: "x + y = 6", equation2: "3x + 3y = 18" },
        { equation1: "x + y = 4", equation2: "x + y = 9" },
        { equation1: "x + y = 10", equation2: "2x - y = 5" },
        { equation1: "4x + y = 14", equation2: "x - y = 1" },
        { equation1: "2x + y = 9", equation2: "x - 2y = -2" },
        { equation1: "x + 2y = 8", equation2: "3x - y = 3" },
        { equation1: "x + y = 7", equation2: "2x + 2y = 14" },
        { equation1: "x + y = 2", equation2: "x + y = 6" },
        { equation1: "x + y = 12", equation2: "2x - y = 3" },
        { equation1: "5x + y = 20", equation2: "x - y = 4" },
        { equation1: "2x + 3y = 18", equation2: "x - y = 1" },
        { equation1: "x + 3y = 11", equation2: "2x - y = 1" },
        { equation1: "3x + y = 13", equation2: "x - 2y = -4" },
        { equation1: "x + y = 9", equation2: "3x + 3y = 27" },
        { equation1: "x + y = 5", equation2: "x + y = 11" },
        { equation1: "4x + 2y = 16", equation2: "x - y = 1" },
        { equation1: "2x + y = 11", equation2: "x - y = 1" },
        { equation1: "x + 4y = 14", equation2: "3x - y = 2" },
        { equation1: "x + y = 14", equation2: "2x - y = 7" },
        { equation1: "6x + y = 25", equation2: "x - y = 4" },
        { equation1: "3x + 4y = 25", equation2: "x - y = 1" },
        { equation1: "x + 5y = 21", equation2: "2x - y = 9" },
        { equation1: "4x + y = 22", equation2: "x - 3y = -8" },
        { equation1: "x + y = 11", equation2: "3x + 3y = 33" },
        { equation1: "x + y = 6", equation2: "x + y = 13" },
        { equation1: "5x + 3y = 26", equation2: "x - y = 2" },
        { equation1: "3x + y = 16", equation2: "x - y = 4" },
        { equation1: "x + 6y = 20", equation2: "4x - y = 2" },
      ],
    },
    {
      toolId: "systemOf3Equations",
      href: "/mathematics/system-of-3-equations",
      type: "3-var",
      pool: [
        { equation1: "x + y + z = 9", equation2: "2x - y + z = 5", equation3: "x + 2y - z = 4" },
        { equation1: "3x + y - z = 6", equation2: "x - y + 2z = 9", equation3: "2x + 3y + z = 8" },
        { equation1: "x + y + z = 5", equation2: "3x + 3y + 3z = 15", equation3: "x - y + z = 2" },
        { equation1: "x + y + z = 2", equation2: "x + y + z = 6", equation3: "3x + y - z = 1" },
        { equation1: "x + y + z = 12", equation2: "2x - y + z = 7", equation3: "x + 2y - z = 6" },
        { equation1: "2x + y - z = 4", equation2: "x - y + 2z = 10", equation3: "3x + 2y + z = 9" },
        { equation1: "x + y + z = 8", equation2: "2x + y - z = 3", equation3: "x - 2y + z = 1" },
        { equation1: "x + 2y + z = 10", equation2: "2x - y + z = 6", equation3: "x + y - 2z = -1" },
        { equation1: "x + y + z = 4", equation2: "2x + 2y + 2z = 8", equation3: "x - y + z = 2" },
        { equation1: "x + y + z = 3", equation2: "x + y + z = 7", equation3: "2x - y + z = 2" },
        { equation1: "x + y + z = 14", equation2: "2x - y + z = 9", equation3: "x + 2y - z = 8" },
        { equation1: "3x + y - z = 8", equation2: "x - y + 2z = 11", equation3: "2x + 3y + z = 10" },
        { equation1: "x + y + z = 6", equation2: "2x + y - z = 5", equation3: "x - y + 2z = 3" },
        { equation1: "x + 2y + z = 12", equation2: "2x - y + z = 8", equation3: "x + y - 2z = 0" },
        { equation1: "x + y + z = 10", equation2: "3x + 3y + 3z = 30", equation3: "x - y + z = 4" },
        { equation1: "x + y + z = 1", equation2: "x + y + z = 5", equation3: "2x - y + z = 3" },
        { equation1: "2x + y - z = 6", equation2: "x - y + 2z = 12", equation3: "3x + 2y + z = 11" },
        { equation1: "x + y + z = 7", equation2: "2x + y - z = 4", equation3: "x - 2y + z = 2" },
        { equation1: "x + 2y + z = 9", equation2: "2x - y + z = 5", equation3: "x + y - 2z = -2" },
        { equation1: "x + y + z = 15", equation2: "2x - y + z = 10", equation3: "x + 2y - z = 9" },
        { equation1: "x + y + z = 16", equation2: "2x - y + z = 11", equation3: "x + 2y - z = 10" },
        { equation1: "3x + y - z = 10", equation2: "x - y + 2z = 13", equation3: "2x + 3y + z = 12" },
        { equation1: "x + y + z = 9", equation2: "2x + y - z = 6", equation3: "x - y + 2z = 5" },
        { equation1: "x + 2y + z = 14", equation2: "2x - y + z = 10", equation3: "x + y - 2z = 1" },
        { equation1: "x + y + z = 12", equation2: "3x + 3y + 3z = 36", equation3: "x - y + z = 5" },
        { equation1: "x + y + z = 0", equation2: "x + y + z = 4", equation3: "2x - y + z = 2" },
        { equation1: "2x + y - z = 8", equation2: "x - y + 2z = 14", equation3: "3x + 2y + z = 13" },
        { equation1: "x + y + z = 11", equation2: "2x + y - z = 7", equation3: "x - 2y + z = 3" },
        { equation1: "x + 2y + z = 13", equation2: "2x - y + z = 7", equation3: "x + y - 2z = -3" },
        { equation1: "x + y + z = 20", equation2: "2x - y + z = 14", equation3: "x + 2y - z = 13" },
      ],
    },
  ],
};

export function generateDailyChallenge(subject: string): Challenge {
  const pools = CHALLENGE_BANK[subject];
  if (!pools || pools.length === 0) {
    throw new Error(`No challenge bank registered for subject "${subject}"`);
  }
  const tool = pools[Math.floor(Math.random() * pools.length)];
  const item = tool.pool[Math.floor(Math.random() * tool.pool.length)];
  return { toolId: tool.toolId, href: tool.href, type: tool.type, ...item };
}
