export type ChallengeType = "algebra" | "2-var" | "3-var" | "sequence" | "probability";

export interface Challenge {
  toolId: string;
  href: string;
  type: ChallengeType;
  equation1?: string;
  equation2?: string;
  equation3?: string;
  engine?: string;
  params?: Record<string, string>;
}

interface ChallengeBankEntry {
  toolId: string;
  href: string;
  type: ChallengeType;
  engine?: string;
  pool: Array<Pick<Challenge, "equation1" | "equation2" | "equation3" | "params">>;
}

const CHALLENGE_BANK: Record<string, ChallengeBankEntry[]> = {
  algebra: [
    {
      toolId: "linearEquations",
      href: "/mathematics/linear-equations",
      type: "algebra",
      pool: [
        { equation1: "3x + 5 = 2x + 12" },
        { equation1: "4*(x - 3) = 2x + 6" },
        { equation1: "6x - 7 = 4x + 9" },
        { equation1: "x/3 + 2 = 5" },
        { equation1: "7x - 2 = 3x + 18" },
        { equation1: "5x + 4 = 3x + 14" },
        { equation1: "2*(x + 4) = 3x - 1" },
        { equation1: "8x - 3 = 5x + 15" },
        { equation1: "x/4 + 3 = 7" },
        { equation1: "9x - 5 = 4x + 20" },
        { equation1: "3*(x - 5) = x + 3" },
        { equation1: "10x + 1 = 6x + 21" },
        { equation1: "4x + 6 = 22" },
        { equation1: "5*(x - 4) = 15" },
        { equation1: "8x - 3 = 4x + 13" },
        { equation1: "x/4 + 1/2 = 6" },
        { equation1: "6x + 9 = 33" },
        { equation1: "7*(x + 2) = 28" },
        { equation1: "9x - 4 = 5x + 16" },
        { equation1: "|4x - 5| = 11" },
        { equation1: "12x - 8 = 7x + 27" },
        { equation1: "6*(2x - 3) = 4*(x + 6)" },
        { equation1: "x/6 + 5 = 12" },
        { equation1: "15x + 4 = 9x + 40" },
        { equation1: "3*(x + 7) - 5 = 2*(x + 10)" },
        { equation1: "x/3 - 1/2 = 4" },
        { equation1: "20x - 15 = 13x + 20" },
        { equation1: "|5x + 3| = 18" },
        { equation1: "9*(x - 6) = 4x - 9" },
        { equation1: "11x + 7 = 4x + 49" },
      ],
    },
    {
      toolId: "quadraticEquations",
      href: "/mathematics/quadratic-equations",
      type: "algebra",
      pool: [
        { equation1: "x^2 - 7x + 10 = 0" },
        { equation1: "x^2 + 6x = -8" },
        { equation1: "x^2 - 6x + 9 = 0" },
        { equation1: "x^2 + 4x + 13 = 0" },
        { equation1: "3x^2 - 12 = 0" },
        { equation1: "x^2 - 9x + 20 = 0" },
        { equation1: "x^2 + 8x = -15" },
        { equation1: "x^2 - 10x + 25 = 0" },
        { equation1: "x^2 + 2x + 10 = 0" },
        { equation1: "2x^2 - 18 = 0" },
        { equation1: "x^2 - 3x - 4 = 0" },
        { equation1: "x^2 + 7x + 12 = 0" },
        { equation1: "x^2 - 5x - 6 = 0" },
        { equation1: "x^2 + 9x + 18 = 0" },
        { equation1: "2x^2 + 3x - 2 = 0" },
        { equation1: "4x^2 - 4x + 1 = 0" },
        { equation1: "x^2 + 5x + 20 = 0" },
        { equation1: "x^2 - 2x - 15 = 0" },
        { equation1: "5x^2 - 20 = 0" },
        { equation1: "x^2 - 11x + 30 = 0" },
        { equation1: "x^2 - 13x + 40 = 0" },
        { equation1: "x^2 + 11x + 24 = 0" },
        { equation1: "3x^2 - 5x - 2 = 0" },
        { equation1: "6x^2 - 7x + 2 = 0" },
        { equation1: "x^2 + 6x + 25 = 0" },
        { equation1: "x^2 - 4x - 21 = 0" },
        { equation1: "7x^2 - 28 = 0" },
        { equation1: "x^2 - 14x + 49 = 0" },
        { equation1: "2x^2 + 7x + 3 = 0" },
        { equation1: "x^2 + 3x - 40 = 0" },
      ],
    },
    {
      toolId: "logarithmicEquations",
      href: "/mathematics/logarithmic-equations",
      type: "algebra",
      pool: [
        { equation1: "log_2(x+5) + log_2(x-3) = 5" },
        { equation1: "log(x+5) - log(x-2) = 1" },
        { equation1: "ln(x) + ln(x-3) = ln(4)" },
        { equation1: "log_3(x^2-4) = 2" },
        { equation1: "ln(x) = 3" },
        { equation1: "log_2(x+7) + log_2(x-1) = 3" },
        { equation1: "log(x+3) - log(x-1) = 1" },
        { equation1: "ln(x) + ln(x-4) = ln(5)" },
        { equation1: "log_3(x^2-9) = 2" },
        { equation1: "ln(x) = 4" },
        { equation1: "log_2(x-2) + log_2(x+2) = 5" },
        { equation1: "log_5(x+4) = 2" },
        { equation1: "log_2(x) = 5" },
        { equation1: "log(x) = 2" },
        { equation1: "ln(x-1) = 2" },
        { equation1: "log_2(x+9) + log_2(x-7) = 4" },
        { equation1: "log(x+7) - log(x-3) = 1" },
        { equation1: "ln(x) + ln(x-5) = ln(6)" },
        { equation1: "log_3(x^2-16) = 2" },
        { equation1: "log_4(x+12) = 2" },
        { equation1: "log_2(x+11) + log_2(x-5) = 4" },
        { equation1: "log(x+9) - log(x-3) = 1" },
        { equation1: "ln(x) + ln(x-6) = ln(7)" },
        { equation1: "log_3(x^2-25) = 2" },
        { equation1: "ln(x) = 5" },
        { equation1: "log_2(x-4) + log_2(x+4) = 5" },
        { equation1: "log_6(x+9) = 2" },
        { equation1: "log(x+2) - log(x-4) = 1" },
        { equation1: "log_2(x) = 6" },
        { equation1: "ln(x-2) = 3" },
        { equation1: "2^x = 64" },
        { equation1: "3^x = 243" },
        { equation1: "5^x = 125" },
        { equation1: "4^x = 256" },
        { equation1: "2^(x+1) = 32" },
        { equation1: "3^(x-2) = 27" },
        { equation1: "5^(2x) = 25" },
        { equation1: "2^(3x) = 64" },
        { equation1: "3^x = 3^(2x-4)" },
        { equation1: "2^(x-3) = 16" },
        { equation1: "4^(x+1) = 64" },
        { equation1: "9^x = 3^(x+4)" },
        { equation1: "8^x = 2^(x+6)" },
        { equation1: "27^x = 3^(x+8)" },
        { equation1: "16^x = 4^(x+3)" },
        { params: { initial: "2000", ratePercent: "5", time: "3", direction: "growth" } },
        { params: { initial: "800", ratePercent: "10", time: "6", direction: "decay" } },
        { params: { initial: "1500", ratePercent: "4", time: "8", direction: "growth" } },
        { params: { initial: "300", ratePercent: "15", time: "5", direction: "decay" } },
        { params: { initial: "5000", ratePercent: "2", time: "10", direction: "growth" } },
        { params: { initial: "1000", ratePercent: "20", time: "3", direction: "decay" } },
        { params: { initial: "250", ratePercent: "8", time: "7", direction: "growth" } },
        { params: { initial: "10000", ratePercent: "6", time: "4", direction: "decay" } },
        { params: { initial: "400", ratePercent: "12", time: "6", direction: "growth" } },
        { params: { initial: "3000", ratePercent: "5", time: "9", direction: "decay" } },
        { params: { initial: "600", ratePercent: "25", time: "2", direction: "growth" } },
        { params: { initial: "7000", ratePercent: "3", time: "12", direction: "decay" } },
        { params: { initial: "150", ratePercent: "18", time: "4", direction: "growth" } },
        { params: { initial: "900", ratePercent: "7", time: "5", direction: "decay" } },
        { params: { initial: "2500", ratePercent: "9", time: "6", direction: "growth" } },
      ],
    },
    {
      toolId: "powersAlgebra",
      href: "/mathematics/exponents-algebra",
      type: "algebra",
      pool: [
        { equation1: "x^3 * x^2" },
        { equation1: "(x^3)^2" },
        { equation1: "x^-3" },
        { equation1: "(x+2)*(x-2)" },
        { equation1: "3x+4=13" },
        { equation1: "2^(2x)+2^x-12=0" },
        { equation1: "x^4 * x^2" },
        { equation1: "(x^2)^4" },
        { equation1: "x^-4" },
        { equation1: "(x+3)*(x-3)" },
        { equation1: "5x+2=17" },
        { equation1: "2^(2x)+2^x-20=0" },
        { equation1: "x^5 * x^3" },
        { equation1: "(x^4)^2" },
        { equation1: "x^-5" },
        { equation1: "(x+4)*(x-4)" },
        { equation1: "6x+3=27" },
        { equation1: "x^2=25" },
        { equation1: "x^3=64" },
        { equation1: "sqrt(2^X) = 8" },
        { equation1: "x^6 * x^2" },
        { equation1: "(x^5)^2" },
        { equation1: "x^-6" },
        { equation1: "(x+5)*(x-5)" },
        { equation1: "7x+5=40" },
        { equation1: "x^2=49" },
        { equation1: "x^3=125" },
        { equation1: "sqrt(3^X) = 27" },
        { equation1: "2^(2x)+2^x-30=0" },
        { equation1: "(x^3)^3" },
      ],
    },
    {
      toolId: "functionAnalysis",
      href: "/mathematics/function-analysis",
      type: "algebra",
      pool: [
        { equation1: "x^3 - 4x^2" },
        { equation1: "x^3 - 4x + 2" },
        { equation1: "x^4 - 9x^2" },
        { equation1: "-x^2 + 6x" },
        { equation1: "x^3 - 9x^2 + 20x" },
        { equation1: "x^3 - 5x^2" },
        { equation1: "x^3 - 5x + 3" },
        { equation1: "x^4 - 16x^2" },
        { equation1: "-x^2 + 8x" },
        { equation1: "x^3 - 12x^2 + 36x" },
        { equation1: "x^3 + 3x^2" },
        { equation1: "x^4 - 4x^2 + 3" },
        { equation1: "x^3 - 6x^2" },
        { equation1: "x^3 - 6x + 4" },
        { equation1: "x^4 - 25x^2" },
        { equation1: "-x^2 + 10x" },
        { equation1: "x^3 - 15x^2 + 56x" },
        { equation1: "x^3 + 4x^2" },
        { equation1: "x^4 - 6x^2 + 5" },
        { equation1: "x^3 - 7x^2 + 10x" },
        { equation1: "x^3 - 8x^2" },
        { equation1: "x^3 - 8x + 6" },
        { equation1: "x^4 - 36x^2" },
        { equation1: "-x^2 + 12x" },
        { equation1: "x^3 - 18x^2 + 80x" },
        { equation1: "x^3 + 5x^2" },
        { equation1: "x^4 - 8x^2 + 7" },
        { equation1: "x^3 - 10x^2 + 21x" },
        { equation1: "x^4 - 49x^2" },
        { equation1: "-x^2 + 14x" },
      ],
    },
    {
      toolId: "systemOfEquations",
      href: "/mathematics/system-of-equations",
      type: "2-var",
      pool: [
        { equation1: "x + y = 8", equation2: "2x - y = 4" },
        { equation1: "3x + 2y = 16", equation2: "x - y = 2" },
        { equation1: "x + y = 6", equation2: "3x + 3y = 18" },
        { equation1: "x + y = 4", equation2: "x + y = 9" },
        { equation1: "x + y = 10", equation2: "2x - y = 5" },
        { equation1: "4x + y = 14", equation2: "x - y = 1" },
        { equation1: "2x + y = 9", equation2: "x - 2y = -2" },
        { equation1: "x + 2y = 8", equation2: "3x - y = 3" },
        { equation1: "x + y = 7", equation2: "2x + 2y = 14" },
        { equation1: "x + y = 2", equation2: "x + y = 6" },
        { equation1: "x + y = 12", equation2: "2x - y = 3" },
        { equation1: "5x + y = 20", equation2: "x - y = 4" },
        { equation1: "2x + 3y = 18", equation2: "x - y = 1" },
        { equation1: "x + 3y = 11", equation2: "2x - y = 1" },
        { equation1: "3x + y = 13", equation2: "x - 2y = -4" },
        { equation1: "x + y = 9", equation2: "3x + 3y = 27" },
        { equation1: "x + y = 5", equation2: "x + y = 11" },
        { equation1: "4x + 2y = 16", equation2: "x - y = 1" },
        { equation1: "2x + y = 11", equation2: "x - y = 1" },
        { equation1: "x + 4y = 14", equation2: "3x - y = 2" },
        { equation1: "x + y = 14", equation2: "2x - y = 7" },
        { equation1: "6x + y = 25", equation2: "x - y = 4" },
        { equation1: "3x + 4y = 25", equation2: "x - y = 1" },
        { equation1: "x + 5y = 21", equation2: "2x - y = 9" },
        { equation1: "4x + y = 22", equation2: "x - 3y = -8" },
        { equation1: "x + y = 11", equation2: "3x + 3y = 33" },
        { equation1: "x + y = 6", equation2: "x + y = 13" },
        { equation1: "5x + 3y = 26", equation2: "x - y = 2" },
        { equation1: "3x + y = 16", equation2: "x - y = 4" },
        { equation1: "x + 6y = 20", equation2: "4x - y = 2" },
      ],
    },
    {
      toolId: "systemOf3Equations",
      href: "/mathematics/system-of-3-equations",
      type: "3-var",
      pool: [
        { equation1: "x + y + z = 9", equation2: "2x - y + z = 5", equation3: "x + 2y - z = 4" },
        { equation1: "3x + y - z = 6", equation2: "x - y + 2z = 9", equation3: "2x + 3y + z = 8" },
        { equation1: "x + y + z = 5", equation2: "3x + 3y + 3z = 15", equation3: "x - y + z = 2" },
        { equation1: "x + y + z = 2", equation2: "x + y + z = 6", equation3: "3x + y - z = 1" },
        { equation1: "x + y + z = 12", equation2: "2x - y + z = 7", equation3: "x + 2y - z = 6" },
        { equation1: "2x + y - z = 4", equation2: "x - y + 2z = 10", equation3: "3x + 2y + z = 9" },
        { equation1: "x + y + z = 8", equation2: "2x + y - z = 3", equation3: "x - 2y + z = 1" },
        { equation1: "x + 2y + z = 10", equation2: "2x - y + z = 6", equation3: "x + y - 2z = -1" },
        { equation1: "x + y + z = 4", equation2: "2x + 2y + 2z = 8", equation3: "x - y + z = 2" },
        { equation1: "x + y + z = 3", equation2: "x + y + z = 7", equation3: "2x - y + z = 2" },
        { equation1: "x + y + z = 14", equation2: "2x - y + z = 9", equation3: "x + 2y - z = 8" },
        { equation1: "3x + y - z = 8", equation2: "x - y + 2z = 11", equation3: "2x + 3y + z = 10" },
        { equation1: "x + y + z = 6", equation2: "2x + y - z = 5", equation3: "x - y + 2z = 3" },
        { equation1: "x + 2y + z = 12", equation2: "2x - y + z = 8", equation3: "x + y - 2z = 0" },
        { equation1: "x + y + z = 10", equation2: "3x + 3y + 3z = 30", equation3: "x - y + z = 4" },
        { equation1: "x + y + z = 1", equation2: "x + y + z = 5", equation3: "2x - y + z = 3" },
        { equation1: "2x + y - z = 6", equation2: "x - y + 2z = 12", equation3: "3x + 2y + z = 11" },
        { equation1: "x + y + z = 7", equation2: "2x + y - z = 4", equation3: "x - 2y + z = 2" },
        { equation1: "x + 2y + z = 9", equation2: "2x - y + z = 5", equation3: "x + y - 2z = -2" },
        { equation1: "x + y + z = 15", equation2: "2x - y + z = 10", equation3: "x + 2y - z = 9" },
        { equation1: "x + y + z = 16", equation2: "2x - y + z = 11", equation3: "x + 2y - z = 10" },
        { equation1: "3x + y - z = 10", equation2: "x - y + 2z = 13", equation3: "2x + 3y + z = 12" },
        { equation1: "x + y + z = 9", equation2: "2x + y - z = 6", equation3: "x - y + 2z = 5" },
        { equation1: "x + 2y + z = 14", equation2: "2x - y + z = 10", equation3: "x + y - 2z = 1" },
        { equation1: "x + y + z = 12", equation2: "3x + 3y + 3z = 36", equation3: "x - y + z = 5" },
        { equation1: "x + y + z = 0", equation2: "x + y + z = 4", equation3: "2x - y + z = 2" },
        { equation1: "2x + y - z = 8", equation2: "x - y + 2z = 14", equation3: "3x + 2y + z = 13" },
        { equation1: "x + y + z = 11", equation2: "2x + y - z = 7", equation3: "x - 2y + z = 3" },
        { equation1: "x + 2y + z = 13", equation2: "2x - y + z = 7", equation3: "x + y - 2z = -3" },
        { equation1: "x + y + z = 20", equation2: "2x - y + z = 14", equation3: "x + 2y - z = 13" },
      ],
    },
    {
      toolId: "complexNumbers",
      href: "/mathematics/complex-numbers",
      type: "algebra",
      pool: [
        { equation1: "z^2 + 2z + 5 = 0" },
        { equation1: "z^2 + 6z + 25 = 0" },
        { equation1: "z^2 + 8z + 20 = 0" },
        { equation1: "z^2 + 2z + 10 = 0" },
        { equation1: "z^2 + 10z + 34 = 0" },
        { equation1: "z^2 + 4z + 8 = 0" },
        { equation1: "z^2 + 6z + 13 = 0" },
        { equation1: "z^2 + 16 = 0" },
        { equation1: "z^2 + 25 = 0" },
        { equation1: "z^2 + 4 = 0" },
        { equation1: "z^2 + 2z + 2 = 0" },
        { equation1: "z^2 + 4z + 5 = 0" },
        { equation1: "z^2 + 8z + 17 = 0" },
        { equation1: "z^2 + 12z + 37 = 0" },
        { equation1: "3z^2 + 12 = 0" },
        { equation1: "2z^2 + 4z + 10 = 0" },
        { equation1: "5z^2 + 20 = 0" },
        { equation1: "z^2 - 5z + 6 = 0" },
        { equation1: "z^2 - 7z + 10 = 0" },
        { equation1: "z^2 - 1 = 0" },
        { equation1: "z^2 - 9 = 0" },
        { equation1: "z^2 - 3z - 4 = 0" },
        { equation1: "z^2 + z - 6 = 0" },
        { equation1: "z^2 - 6z + 8 = 0" },
        { equation1: "2z^2 - 8 = 0" },
        { equation1: "z^2 - 8z + 15 = 0" },
        { equation1: "z^2 - 2z - 8 = 0" },
        { equation1: "z^2 - 4 = 0" },
        { equation1: "z^2 + 14z + 50 = 0" },
        { equation1: "z^2 - 14z + 50 = 0" },
      ],
    },
    {
      toolId: "circleGeometry",
      href: "/mathematics/circle-geometry",
      type: "algebra",
      pool: [
        { equation1: "x^2+y^2-6x-16=0" },
        { equation1: "x^2+y^2-8y-9=0" },
        { equation1: "x^2+y^2+4x-6y-23=0" },
        { equation1: "x^2+y^2-10x+2y+17=0" },
        { equation1: "x^2+y^2+6x+8y-75=0" },
        { equation1: "x^2+y^2-2x-2y-2=0" },
        { equation1: "x^2+y^2-49=0" },
        { equation1: "x^2+y^2-8x-8y+7=0" },
        { equation1: "x^2+y^2+2x-4y-4=0" },
        { equation1: "x^2+y^2-12x+4y-9=0" },
        { equation1: "x^2+y^2-4x-4y+4=0" },
        { equation1: "x^2+y^2+10x=0" },
        { equation1: "x^2+y^2+12y=0" },
        { equation1: "x^2+y^2-6x+6y+9=0" },
        { equation1: "x^2+y^2-2x+8y-8=0" },
        { equation1: "(x-1)^2+(y-2)^2=9" },
        { equation1: "(x+2)^2+(y-1)^2=25" },
        { equation1: "(x-4)^2+(y+5)^2=36" },
        { equation1: "(x+3)^2+(y+3)^2=4" },
        { equation1: "(x-6)^2+y^2=49" },
        { equation1: "x^2+(y-7)^2=16" },
        { equation1: "(x+1)^2+(y-6)^2=100" },
        { equation1: "(x-2)^2+(y-2)^2=1" },
        { equation1: "(x+5)^2+(y-2)^2=64" },
        { equation1: "(x-3)^2+(y+1)^2=81" },
        { equation1: "(x+4)^2+(y+4)^2=9" },
        { equation1: "(x-5)^2+(y-5)^2=16" },
        { equation1: "(x+2)^2+(y+2)^2=25" },
        { equation1: "(x-7)^2+y^2=36" },
        { equation1: "x^2+(y+8)^2=4" },
      ],
    },
  ],
  probabilitySequences: [
    {
      toolId: "arithmeticSequences",
      href: "/mathematics/arithmetic-sequences",
      type: "sequence",
      pool: [
        { params: { a1: "2", d: "3", n: "10" } },
        { params: { a1: "5", d: "-2", n: "12" } },
        { params: { a1: "1", n: "8", an: "22" } },
        { params: { a1: "10", d: "4", n: "9" } },
        { params: { a1: "-3", d: "5", n: "11" } },
        { params: { a1: "7", n: "6", an: "-8" } },
        { params: { a1: "0", d: "6", n: "14" } },
        { params: { a1: "20", d: "-3", n: "8" } },
        { params: { a1: "4", n: "10", an: "40" } },
        { params: { a1: "-5", d: "2", n: "15" } },
        { params: { a1: "100", d: "-10", n: "7" } },
        { params: { a1: "3", n: "7", an: "27" } },
        { params: { a1: "0.5", d: "0.5", n: "10" } },
        { params: { a1: "15", d: "3", n: "12" } },
        { params: { a1: "9", n: "5", an: "-3" } },
        { params: { a1: "-2", d: "-4", n: "9" } },
        { params: { a1: "6", d: "7", n: "13" } },
        { params: { a1: "2", n: "9", an: "34" } },
        { params: { a1: "50", d: "-5", n: "11" } },
        { params: { a1: "1", d: "1", n: "20" } },
        { params: { a1: "8", n: "12", an: "41" } },
        { params: { a1: "-10", d: "3", n: "14" } },
        { params: { a1: "25", d: "-2", n: "10" } },
        { params: { a1: "3", n: "15", an: "59" } },
        { params: { a1: "0", d: "2", n: "25" } },
        { params: { a1: "12", d: "-6", n: "6" } },
        { params: { a1: "7", n: "11", an: "57" } },
        { params: { a1: "-1", d: "4", n: "16" } },
        { params: { a1: "40", d: "5", n: "9" } },
        { params: { a1: "6", n: "8", an: "-15" } },
      ],
    },
    {
      toolId: "geometricSequences",
      href: "/mathematics/geometric-sequences",
      type: "sequence",
      pool: [
        { params: { a1: "3", q: "2", n: "8" } },
        { params: { a1: "2", q: "3", n: "6" } },
        { params: { a1: "64", q: "0.5", n: "7" } },
        { params: { a1: "5", q: "-2", n: "6" } },
        { params: { a1: "1", q: "4", n: "5" } },
        { params: { a1: "100", q: "0.1", n: "4" } },
        { params: { a1: "2", n: "5", an: "32" } },
        { params: { a1: "7", q: "2", n: "5" } },
        { params: { a1: "10", q: "-3", n: "5" } },
        { params: { a1: "1", q: "2", n: "10" } },
        { params: { a1: "3", n: "4", an: "81" } },
        { params: { a1: "16", q: "0.5", n: "6" } },
        { params: { a1: "5", q: "3", n: "5" } },
        { params: { a1: "2", q: "-3", n: "4" } },
        { params: { a1: "9", n: "3", an: "81" } },
        { params: { a1: "1000", q: "0.1", n: "3" } },
        { params: { a1: "4", q: "2", n: "9" } },
        { params: { a1: "6", q: "-2", n: "5" } },
        { params: { a1: "1", q: "5", n: "4" } },
        { params: { a1: "2", n: "6", an: "64" } },
        { params: { a1: "81", q: "0.5", n: "5" } },
        { params: { a1: "3", q: "4", n: "5" } },
        { params: { a1: "12", q: "-2", n: "5" } },
        { params: { a1: "1", q: "3", n: "6" } },
        { params: { a1: "5", n: "4", an: "625" } },
        { params: { a1: "200", q: "0.5", n: "5" } },
        { params: { a1: "2", q: "2", n: "12" } },
        { params: { a1: "7", q: "-2", n: "4" } },
        { params: { a1: "3", n: "5", an: "243" } },
        { params: { a1: "10", q: "2", n: "6" } },
      ],
    },
    {
      toolId: "probabilityStatistics",
      href: "/mathematics/probability-statistics?engine=classical",
      type: "probability",
      engine: "classical",
      pool: [
        { params: { favorable: "1", total: "6" } },
        { params: { favorable: "3", total: "6" } },
        { params: { favorable: "4", total: "52" } },
        { params: { favorable: "13", total: "52" } },
        { params: { favorable: "2", total: "5" } },
        { params: { favorable: "7", total: "10" } },
        { params: { favorable: "1", total: "2" } },
        { params: { favorable: "5", total: "36" } },
        { params: { favorable: "6", total: "36" } },
        { params: { favorable: "3", total: "20" } },
        { params: { favorable: "9", total: "15" } },
        { params: { favorable: "2", total: "13" } },
        { params: { favorable: "11", total: "52" } },
        { params: { favorable: "4", total: "9" } },
        { params: { favorable: "1", total: "100" } },
        { params: { favorable: "25", total: "100" } },
        { params: { favorable: "3", total: "4" } },
        { params: { favorable: "8", total: "36" } },
        { params: { favorable: "6", total: "11" } },
        { params: { favorable: "5", total: "8" } },
        { params: { favorable: "2", total: "7" } },
        { params: { favorable: "10", total: "30" } },
        { params: { favorable: "18", total: "40" } },
        { params: { favorable: "1", total: "10" } },
        { params: { favorable: "7", total: "12" } },
        { params: { favorable: "12", total: "52" } },
        { params: { favorable: "4", total: "16" } },
        { params: { favorable: "20", total: "25" } },
        { params: { favorable: "3", total: "14" } },
        { params: { favorable: "9", total: "50" } },
      ],
    },
    {
      toolId: "probabilityStatistics",
      href: "/mathematics/probability-statistics?engine=conditional",
      type: "probability",
      engine: "conditional",
      pool: [
        { params: { pAB: "0.3", pAnotB: "0.2", pnotAB: "0.1", pnotAnotB: "0.4" } },
        { params: { pAB: "0.15", pAnotB: "0.25", pnotAB: "0.35", pnotAnotB: "0.25" } },
        { params: { pAB: "0.4", pAnotB: "0.1", pnotAB: "0.2", pnotAnotB: "0.3" } },
        { params: { pAB: "0.05", pAnotB: "0.15", pnotAB: "0.35", pnotAnotB: "0.45" } },
        { params: { pAB: "0.2", pAnotB: "0.3", pnotAB: "0.1", pnotAnotB: "0.4" } },
        { params: { pAB: "0.1", pAnotB: "0.4", pnotAB: "0.2", pnotAnotB: "0.3" } },
        { params: { pAB: "0.25", pAnotB: "0.25", pnotAB: "0.25", pnotAnotB: "0.25" } },
        { params: { pAB: "0.5", pAnotB: "0.1", pnotAB: "0.1", pnotAnotB: "0.3" } },
        { params: { pAB: "0.12", pAnotB: "0.18", pnotAB: "0.28", pnotAnotB: "0.42" } },
        { params: { pAB: "0.35", pAnotB: "0.15", pnotAB: "0.15", pnotAnotB: "0.35" } },
        { params: { pAB: "0.08", pAnotB: "0.32", pnotAB: "0.12", pnotAnotB: "0.48" } },
        { params: { pAB: "0.45", pAnotB: "0.05", pnotAB: "0.25", pnotAnotB: "0.25" } },
        { params: { pAB: "0.3", pAnotB: "0.3", pnotAB: "0.2", pnotAnotB: "0.2" } },
        { params: { pAB: "0.18", pAnotB: "0.22", pnotAB: "0.12", pnotAnotB: "0.48" } },
        { params: { pAB: "0.6", pAnotB: "0.1", pnotAB: "0.1", pnotAnotB: "0.2" } },
        { params: { pAB: "0.1", pAnotB: "0.1", pnotAB: "0.4", pnotAnotB: "0.4" } },
        { params: { pAB: "0.22", pAnotB: "0.18", pnotAB: "0.38", pnotAnotB: "0.22" } },
        { params: { pAB: "0.05", pAnotB: "0.45", pnotAB: "0.05", pnotAnotB: "0.45" } },
        { params: { pAB: "0.4", pAnotB: "0.2", pnotAB: "0.3", pnotAnotB: "0.1" } },
        { params: { pAB: "0.15", pAnotB: "0.35", pnotAB: "0.15", pnotAnotB: "0.35" } },
        { params: { pAB: "0.28", pAnotB: "0.12", pnotAB: "0.22", pnotAnotB: "0.38" } },
        { params: { pAB: "0.5", pAnotB: "0.2", pnotAB: "0.2", pnotAnotB: "0.1" } },
        { params: { pAB: "0.05", pAnotB: "0.2", pnotAB: "0.3", pnotAnotB: "0.45" } },
        { params: { pAB: "0.33", pAnotB: "0.17", pnotAB: "0.27", pnotAnotB: "0.23" } },
        { params: { pAB: "0.1", pAnotB: "0.3", pnotAB: "0.3", pnotAnotB: "0.3" } },
        { params: { pAB: "0.2", pAnotB: "0.2", pnotAB: "0.2", pnotAnotB: "0.4" } },
        { params: { pAB: "0.42", pAnotB: "0.08", pnotAB: "0.18", pnotAnotB: "0.32" } },
        { params: { pAB: "0.16", pAnotB: "0.24", pnotAB: "0.34", pnotAnotB: "0.26" } },
        { params: { pAB: "0.36", pAnotB: "0.14", pnotAB: "0.24", pnotAnotB: "0.26" } },
        { params: { pAB: "0.09", pAnotB: "0.21", pnotAB: "0.31", pnotAnotB: "0.39" } },
      ],
    },
    {
      toolId: "probabilityStatistics",
      href: "/mathematics/probability-statistics?engine=binomial",
      type: "probability",
      engine: "binomial",
      pool: [
        { params: { n: "5", k: "2", p: "0.5" } },
        { params: { n: "10", k: "3", p: "0.3" } },
        { params: { n: "6", k: "4", p: "0.6" } },
        { params: { n: "8", k: "2", p: "0.25" } },
        { params: { n: "4", k: "0", p: "0.2" } },
        { params: { n: "12", k: "5", p: "0.4" } },
        { params: { n: "7", k: "7", p: "0.9" } },
        { params: { n: "5", k: "1", p: "0.1" } },
        { params: { n: "9", k: "3", p: "0.5" } },
        { params: { n: "6", k: "2", p: "0.7" } },
        { params: { n: "10", k: "6", p: "0.6" } },
        { params: { n: "15", k: "4", p: "0.2" } },
        { params: { n: "3", k: "1", p: "0.5" } },
        { params: { n: "20", k: "10", p: "0.5" } },
        { params: { n: "8", k: "5", p: "0.45" } },
        { params: { n: "6", k: "0", p: "0.3" } },
        { params: { n: "11", k: "7", p: "0.55" } },
        { params: { n: "4", k: "2", p: "0.8" } },
        { params: { n: "14", k: "6", p: "0.35" } },
        { params: { n: "5", k: "5", p: "0.9" } },
        { params: { n: "9", k: "5", p: "0.5" } },
        { params: { n: "10", k: "1", p: "0.05" } },
        { params: { n: "7", k: "3", p: "0.4" } },
        { params: { n: "13", k: "8", p: "0.6" } },
        { params: { n: "6", k: "3", p: "0.5" } },
        { params: { n: "16", k: "9", p: "0.45" } },
        { params: { n: "5", k: "3", p: "0.65" } },
        { params: { n: "18", k: "12", p: "0.7" } },
        { params: { n: "8", k: "0", p: "0.15" } },
        { params: { n: "12", k: "8", p: "0.75" } },
      ],
    },
    {
      toolId: "probabilityStatistics",
      href: "/mathematics/probability-statistics?engine=descriptive",
      type: "probability",
      engine: "descriptive",
      pool: [
        { params: { mode: "list", listText: "4, 7, 7, 9, 12" } },
        { params: { mode: "freq", freqText: "4:2, 7:3, 9:1" } },
        { params: { mode: "list", listText: "2, 4, 4, 6, 8, 10" } },
        { params: { mode: "list", listText: "10, 12, 15, 15, 18, 20, 22" } },
        { params: { mode: "freq", freqText: "1:1, 2:2, 3:4, 4:2, 5:1" } },
        { params: { mode: "list", listText: "5, 5, 5, 8, 9" } },
        { params: { mode: "list", listText: "100, 95, 90, 85, 80" } },
        { params: { mode: "freq", freqText: "10:5, 20:3, 30:2" } },
        { params: { mode: "list", listText: "3, 6, 9, 12, 15" } },
        { params: { mode: "list", listText: "1, 2, 3, 4, 5, 6, 7, 8, 9, 10" } },
        { params: { mode: "freq", freqText: "2:3, 4:5, 6:2" } },
        { params: { mode: "list", listText: "7, 8, 8, 9, 10, 10, 10, 11" } },
        { params: { mode: "list", listText: "25, 30, 35, 40, 45, 50" } },
        { params: { mode: "freq", freqText: "5:4, 10:6, 15:2" } },
        { params: { mode: "list", listText: "-3, -1, 0, 2, 5" } },
        { params: { mode: "list", listText: "50, 60, 60, 70, 80, 90" } },
        { params: { mode: "freq", freqText: "3:2, 6:3, 9:4, 12:1" } },
        { params: { mode: "list", listText: "12, 14, 14, 16, 18, 20" } },
        { params: { mode: "list", listText: "1.5, 2.5, 3.5, 4.5, 5.5" } },
        { params: { mode: "freq", freqText: "1:10, 2:15, 3:5" } },
        { params: { mode: "list", listText: "8, 9, 10, 11, 12, 13, 14" } },
        { params: { mode: "list", listText: "200, 210, 220, 230, 240" } },
        { params: { mode: "freq", freqText: "0:3, 1:6, 2:9, 3:2" } },
        { params: { mode: "list", listText: "6, 6, 6, 6, 10" } },
        { params: { mode: "list", listText: "33, 35, 37, 39, 41, 43" } },
        { params: { mode: "freq", freqText: "20:1, 25:2, 30:3, 35:4" } },
        { params: { mode: "list", listText: "9, 11, 13, 15, 17, 19" } },
        { params: { mode: "list", listText: "0, 5, 10, 15, 20, 25, 30" } },
        { params: { mode: "freq", freqText: "7:2, 14:2, 21:2" } },
        { params: { mode: "list", listText: "45, 50, 55, 60, 65, 70, 75" } },
      ],
    },
    {
      toolId: "probabilityStatistics",
      href: "/mathematics/probability-statistics?engine=normal",
      type: "probability",
      engine: "normal",
      pool: [
        { params: { mu: "100", sigma: "15", mode: "below", x: "120" } },
        { params: { mu: "50", sigma: "10", mode: "above", x: "65" } },
        { params: { mu: "0", sigma: "1", mode: "between", x: "-1", x2: "1" } },
        { params: { mu: "70", sigma: "8", mode: "below", x: "75" } },
        { params: { mu: "500", sigma: "100", mode: "above", x: "600" } },
        { params: { mu: "20", sigma: "5", mode: "between", x: "15", x2: "25" } },
        { params: { mu: "10", sigma: "2", mode: "below", x: "12" } },
        { params: { mu: "60", sigma: "12", mode: "above", x: "48" } },
        { params: { mu: "100", sigma: "15", mode: "between", x: "85", x2: "115" } },
        { params: { mu: "0", sigma: "1", mode: "below", x: "1.96" } },
        { params: { mu: "30", sigma: "6", mode: "above", x: "36" } },
        { params: { mu: "200", sigma: "25", mode: "between", x: "175", x2: "225" } },
        { params: { mu: "12", sigma: "3", mode: "below", x: "9" } },
        { params: { mu: "80", sigma: "10", mode: "above", x: "90" } },
        { params: { mu: "5", sigma: "1", mode: "between", x: "4", x2: "6" } },
        { params: { mu: "1000", sigma: "200", mode: "below", x: "1200" } },
        { params: { mu: "40", sigma: "5", mode: "above", x: "45" } },
        { params: { mu: "25", sigma: "4", mode: "between", x: "20", x2: "30" } },
        { params: { mu: "0", sigma: "1", mode: "below", x: "-1.5" } },
        { params: { mu: "150", sigma: "20", mode: "above", x: "130" } },
        { params: { mu: "18", sigma: "3", mode: "between", x: "15", x2: "21" } },
        { params: { mu: "90", sigma: "7", mode: "below", x: "100" } },
        { params: { mu: "45", sigma: "9", mode: "above", x: "54" } },
        { params: { mu: "60", sigma: "8", mode: "between", x: "52", x2: "68" } },
        { params: { mu: "110", sigma: "18", mode: "below", x: "130" } },
        { params: { mu: "75", sigma: "11", mode: "above", x: "86" } },
        { params: { mu: "3", sigma: "0.5", mode: "between", x: "2.5", x2: "3.5" } },
        { params: { mu: "500", sigma: "50", mode: "below", x: "450" } },
        { params: { mu: "22", sigma: "4", mode: "above", x: "26" } },
        { params: { mu: "88", sigma: "6", mode: "between", x: "82", x2: "94" } },
      ],
    },
  ],
};

export function generateDailyChallenge(subject: string): Challenge {
  const pools = CHALLENGE_BANK[subject];
  if (!pools || pools.length === 0) {
    throw new Error(`No challenge bank registered for subject "${subject}"`);
  }
  const tool = pools[Math.floor(Math.random() * pools.length)];
  const item = tool.pool[Math.floor(Math.random() * tool.pool.length)];
  return { toolId: tool.toolId, href: tool.href, type: tool.type, engine: tool.engine, ...item };
}
